"""Tests for the continuum slope estimator, written against the two ways it can lie.

The estimator has exactly two failure modes worth testing, and neither is caught by
checking that it recovers a slope from clean data:

  * it can report a slope that is BIASED, which is what the log-space predecessor did by
    silently requiring f > 0 and thereby keeping only upward noise excursions;
  * it can report a slope where NO SLOPE IS IDENTIFIABLE, which is what the unguarded
    linear-space version did when the continuum amplitude was consistent with zero.

Both are tested against cases with a KNOWN answer rather than against a stored baseline,
because a regression baseline generated by a buggy estimator simply freezes the bug.
"""

from __future__ import annotations

import numpy as np
import pytest

from redress.slopefit import BETA_GRID, MIN_CONTINUUM_SNR, fit_powerlaw

LAM = np.linspace(3645.0, 7000.0, 120)


def _powerlaw(beta: float, amp: float = 1.0) -> np.ndarray:
    out = amp * (LAM / 5000.0) ** beta
    return out


def test_a_clean_power_law_returns_its_own_exponent():
    """The floor: a noiseless power law must come back as itself, to grid resolution."""
    for beta in (-3.0, -2.0, -0.5, 0.0, 1.0):
        f = _powerlaw(beta)
        e = np.full_like(f, 1e-6)
        r = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
        assert r["ok"], r["reason"]
        assert r["beta"] == pytest.approx(beta, abs=0.03)


def test_the_fit_is_invariant_to_the_units_of_the_flux():
    """Rescaling every flux and error by the same factor changes the amplitude and nothing
    else. A slope that moved under a unit change would be measuring the unit."""
    rng = np.random.default_rng(11)
    f = _powerlaw(-1.5) + rng.normal(0.0, 0.02, LAM.size)
    e = np.full_like(f, 0.02)
    a = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
    b = fit_powerlaw(LAM, 1e6 * f, 1e6 * e, 3000.0, 8000.0)
    assert a["ok"] and b["ok"]
    assert b["beta"] == pytest.approx(a["beta"], abs=1e-9)
    assert b["beta_lo2"] == pytest.approx(a["beta_lo2"], abs=1e-6)


def test_pure_noise_is_refused_rather_than_assigned_a_slope():
    """THE DEFECT THAT MOTIVATED THE REWRITE (review round S1, CRITICAL 1). With no continuum,
    every exponent predicts the same zero spectrum, so the profile is choosing whichever
    power law best correlates with noise. Reporting that as a measurement is how a
    candidate list fills up with objects that are not there."""
    rng = np.random.default_rng(4)
    refused = 0
    trials = 60
    for _ in range(trials):
        f = rng.normal(0.0, 1.0, LAM.size)
        e = np.ones_like(f)
        r = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
        refused += int(not r["ok"])
    assert refused == trials, f"pure noise produced {trials - refused} slopes"


def test_the_refusal_names_the_guard_that_fired():
    """A refusal nobody can attribute is a refusal nobody can audit."""
    rng = np.random.default_rng(5)
    f = rng.normal(0.0, 1.0, LAM.size)
    r = fit_powerlaw(LAM, f, np.ones_like(f), 3000.0, 8000.0)
    assert not r["ok"]
    assert (
        "continuum not detected" in r["reason"]
        or "edge" in r["reason"]
        or "unstable" in r["reason"]
    )


def test_an_undetected_continuum_is_refused_even_when_the_shape_is_real():
    """A real power law buried under noise is still unmeasurable. The guard keys on the
    AMPLITUDE significance, so it must refuse a faint source regardless of its shape."""
    f = _powerlaw(-2.0, amp=0.01)
    e = np.ones_like(f)
    r = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
    assert not r["ok"]
    assert r["amp_snr"] < MIN_CONTINUUM_SNR


def test_a_grid_edge_minimum_is_never_reported_as_a_measurement():
    """(review round S1, CRITICAL 2.) An exponent past the end of the search grid means the
    profile is still falling; the optimiser has bounded it, not found it. Returning the
    clipped edge value and building an interval around it reports a certainty that was
    never established."""
    steep = 40.0
    f = (LAM / LAM.min()) ** steep
    f = 100.0 * f / f.max()
    e = np.full_like(f, 1e-3)
    r = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
    if not r["ok"]:
        assert "edge" in r["reason"]
    else:
        assert abs(r["beta"]) < BETA_GRID.max()


def test_the_bounds_are_one_sided_and_bracket_the_estimate():
    """(review round S1, HIGH 3.) The criteria use ONE side each -- the optical needs the lower
    bound of beta_opt, the UV the upper bound of beta_UV -- so the two are returned
    separately instead of being averaged into a symmetric sigma that is anti-conservative
    on whichever side the cut happens to use."""
    rng = np.random.default_rng(7)
    f = _powerlaw(-1.0) + rng.normal(0.0, 0.03, LAM.size)
    e = np.full_like(f, 0.03)
    r = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
    assert r["ok"], r["reason"]
    assert r["beta_lo2"] < r["beta"] < r["beta_hi2"]


def test_too_few_pixels_is_refused_before_anything_is_fitted():
    f = _powerlaw(-2.0)[:6]
    lam = LAM[:6]
    r = fit_powerlaw(lam, f, np.full_like(f, 1e-6), 3000.0, 8000.0)
    assert not r["ok"]
    assert "pixels" in r["reason"]


def test_a_short_wavelength_span_is_refused_however_many_pixels_it_has():
    """Pixel count is not information. Fifty pixels crammed into a hundredth of a dex
    carry almost no lever arm on an exponent, and the fit would report a precise number
    from an ill-conditioned design."""
    lam = np.linspace(5000.0, 5050.0, 60)
    f = 1.0 * (lam / 5000.0) ** -2.0
    r = fit_powerlaw(lam, f, np.full_like(f, 1e-6), 3000.0, 8000.0)
    assert not r["ok"]
    assert "span" in r["reason"]


def test_the_log_space_estimator_is_biased_red_at_low_signal_and_this_one_is_not():
    """THE HEADLINE REGRESSION TEST. On a FLAT-f_nu continuum (beta = -2, not red) with
    per-pixel S/N near 1, the log-space fit keeps only pixels the noise pushed positive and
    reports a slope that is too red by of order one. The V-shape criterion is beta_opt > 0,
    so that bias manufactures the exact signal the search is looking for, preferentially in
    faint spectra. This test pins the direction and rough size of both estimators; if the
    linear-space one ever acquires the same bias, this fails."""
    rng = np.random.default_rng(20260828)
    truth = -2.0
    model = _powerlaw(truth)
    model = model / np.median(model)
    sigma = 1.0  # per-pixel S/N about 1 at the median
    log_fits, lin_fits = [], []
    for _ in range(120):
        f = model + rng.normal(0.0, sigma, LAM.size)
        e = np.full_like(f, sigma)
        m = f > 0
        if m.sum() > 10:
            x = np.log10(LAM[m])
            y = np.log10(f[m])
            w = 1.0 / np.clip((e[m] / f[m]) / np.log(10), 1e-6, None) ** 2
            X = np.vstack([x, np.ones_like(x)]).T
            cov = np.linalg.inv(X.T @ (w[:, None] * X))
            log_fits.append(float((cov @ (X.T @ (w * y)))[0]))
        r = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
        if r["ok"]:
            lin_fits.append(r["beta"])

    assert len(log_fits) > 50
    log_bias = float(np.median(log_fits)) - truth
    assert log_bias > 0.5, (
        f"the log-space bias should be large and RED; got {log_bias:.3f}"
    )
    if lin_fits:
        lin_bias = float(np.median(lin_fits)) - truth
        assert abs(lin_bias) < 0.5, f"linear-space estimator drifted: {lin_bias:.3f}"


def test_a_genuine_red_continuum_is_still_recovered():
    """The guards must not simply refuse everything: a well-measured red continuum has to
    survive, or the estimator trades a false-positive problem for a blind one."""
    rng = np.random.default_rng(3)
    f = _powerlaw(1.0, amp=50.0) + rng.normal(0.0, 1.0, LAM.size)
    e = np.ones_like(f)
    r = fit_powerlaw(LAM, f, e, 3000.0, 8000.0)
    assert r["ok"], r["reason"]
    assert r["beta"] == pytest.approx(1.0, abs=0.3)
    assert r["beta_lo2"] > 0.0  # the criterion the optical cut actually applies


def test_the_correlation_inflation_is_reported_and_bounded():
    """Correlated pixels widen the true uncertainty; the block bootstrap measures by how
    much. The factor is reported so it can be quoted, and bounded so a bootstrap failure
    cannot silently widen every interval into uselessness."""
    rng = np.random.default_rng(9)
    f = _powerlaw(-1.0, amp=30.0) + rng.normal(0.0, 1.0, LAM.size)
    r = fit_powerlaw(LAM, f, np.ones_like(f), 3000.0, 8000.0)
    assert r["ok"], r["reason"]
    assert 1.0 <= r["infl"] <= 2.0
